baseURL = 'http://example.org/'
languageCode = 'es'
defaultContentLanguage = 'es'
title = 'My New Hugo Site'
theme =['hugo-theme-relearn']


[Shortcuts-Title]
other = "Más opciones"

[params]
  # Change default color scheme with a variant one.
  themeVariant = [ "relearn-light", "relearn-dark", "neon"]



[[language.es.menu.main]]
[[menu.shortcuts]]
name="<i class='fab fa-php'></i>   Lenguaje php"
identified=""
url="https://php.net"
weight=1

[[menu.shortcuts]]
name="<i class='fab fa-wikipedia-w'></i>   GitHub Ricardo"
identified=""
url="GitHub Ricardo"
weight=2


defaultContentLanguage="es"
[Languages]
    [Languages.es]
        title = "Ejemplo para el uso de idiomas"
        weight = 1
        languageName = "Español"
        contentDir = "content/es"
        [[Languages.es.menu.shortcuts]]
            name = "Centro Publico Enlaces"
            url = "http://cpilosenlaces.com"
            weight= 1
        [[Languages.es.menu.shortcuts]]
            name = "GitHub Ricardo"
            url = "https://github.com/ByRichigan/TareaHugoRicardo"
            weight= 2  

    [Languages.en]
        title = "Example use language"
        weight = 2
        languageName = "English"
        contentDir = "content/en"
        [[Languages.en.menu.shortcuts]]
            name = "Public Center  Enlaces"
            url = "http://cpilosenlaces.com"
            weight= 1
        [[Languages.en.menu.shortcuts]]
            name = "GitHub Ricardo"
            url = "https://github.com/ByRichigan/TareaHugoRicardo"
            weight= 2 
        
    [Languages.fr]
        title = "Example use language"
        weight = 3
        languageName = "Français"
        contentDir = "content/fr"
        [[Languages.fr.menu.shortcuts]]
            name = "Liens du centre public"
            url = "http://cpilosenlaces.com"
            weight= 1
        [[Languages.fr.menu.shortcuts]]
            name = "GitHub Ricardo"
            url = "https://github.com/ByRichigan/TareaHugoRicardo"
            weight= 2

